import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CustomSidebar from "@/components/CustomSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className + " h-full flex"}>
        <div className="min-h-full flex flex-nowrap">
          <CustomSidebar/>
        </div>
        {children}
      </body>
    </html>
  );
}
